CHAPTERS = [
    dict(name='Fill The Calendar',title='Keep the door open.',image='chapter-calendar.jpg',start=0,count=9,code='01',pages=(4,5,6),
         intro='A customer rarely arrives through one tidy channel. They call while you are working, browse after closing, and leave a quote unanswered. Start by making the next step easy wherever they find you.',
         choose='Follow the gap, not the channel.',
         guidance='If calls go unanswered, begin with reception or missed-call recovery. If visitors ask the same questions, begin on the website. If interest fades after a quote, work on follow-up before adding more advertising.',
         question='Where did the last promising inquiry stop?',
         groups=['From first contact to a booking','Keep the opportunity moving'],
         notes=['A booking tool needs your real availability. Bring the calendar and the rules you use to accept a job.','Look at the whole path: the inquiry, your reply, the booking and the next contact. The weakest step is a useful place to begin.']),
    dict(name='Run The Business',title='Give good work\na clear process.',image='chapter-operations.jpg',start=9,count=9,code='02',pages=(7,8,9),
         intro='The job is only part of the work. Notes need turning into reports, approvals need recording, and money needs collecting. A clear process carries those details from the field back into the business.',
         choose='Start with the repeated handoff.',
         guidance='Notice where someone copies, chases or re-enters information. Choose one ordinary job and follow it from dispatch to payment. The best first change often sits at the point where work waits for another person.',
         question='What still needs doing after the customer thinks the job is finished?',
         groups=['Capture the work as it happens','Carry the job through to payment'],
         notes=['Bring one finished report, one typical job and the steps your crew must follow. Real examples make the setup specific.','Choose the step that is hardest to keep consistent: approvals, optional work, payment, records or dispatch.']),
    dict(name='Look Bigger Than You Are',title='Make your reputation\neasy to find.',image='chapter-presence.jpg',start=18,count=12,code='03',pages=(10,11,12),
         intro='Customers judge what they can see. A clear website, a useful local page and an attentive response to a review all help them understand your business before they speak to you.',
         choose='Fix the destination before sending more traffic.',
         guidance='A new campaign cannot explain a confusing website for you. Start with the page a customer lands on, the places they search and the evidence they use to decide whether to call.',
         question='Would a first-time visitor know what you do and what to do next?',
         groups=['Build a useful place to land','Be visible, credible and responsive'],
         notes=['Gather your service area, core offers, current website and a few examples of work you are proud to show.','Reviews, search and customer experience support one another. Choose the first change around the evidence customers currently see.']),
    dict(name='Be Everywhere Without Working More',title='Put one good idea\nto work in more places.',image='chapter-content.jpg',start=30,count=12,code='04',pages=(13,14,15),
         intro='You already have useful things to say: what happened on a job, how a problem was solved, what a customer should know. The work is turning that knowledge into a steady presence and a useful conversation.',
         choose='Choose a rhythm you can feed.',
         guidance='If speaking comes easily, start with a voice memo. If the work is visual, start with a short video. Then decide where the message belongs and which replies need your attention.',
         question='What do you explain to a customer over and over?',
         groups=['Create once. Keep showing up.','Keep every conversation useful'],
         notes=['Bring existing photos, recordings or a few sentences that sound like you. Your everyday expertise is the source material.','Separate routine questions and reminders from the conversations that need your judgment. Plan where the handoff happens.']),
    dict(name='Sleep At Night',title='Make the business\nless fragile.',image='chapter-protection.jpg',start=42,count=12,code='05',pages=(16,17,18),
         intro='A dependable business knows where its information lives, how its systems connect and what to do when something fails. It also knows which numbers matter and which recurring bills still earn their place.',
         choose='Start with what would interrupt tomorrow.',
         guidance='Name the records, tools and decisions you depend on. If losing one would stop the day, make its protection or recovery the first conversation. Then untangle duplication and improve visibility.',
         question='If one essential system stopped working, what would you reach for?',
         groups=['Protect essentials. See the numbers.','Connect the tools. Clear the clutter.'],
         notes=['Bring a list of the systems holding customer information, job records and payments, plus any existing recovery instructions.','Review what each tool does before replacing it. A clean connection or a better customer list may resolve more than another subscription.']),
]
# A compact front-of-book route finder, intentionally organized around situations.
ROUTES = [
 ('People are trying to reach you','Calls, website conversations, bookings and follow-up','Fill The Calendar',4),
 ('The work follows you home','Field notes, reports, approvals, payments and dispatch','Run The Business',7),
 ('The business is hard to discover','Websites, local search, maps and reputation','Look Bigger Than You Are',10),
 ('Marketing keeps getting postponed','Writing, social posts, video, campaigns and support','Be Everywhere Without Working More',13),
 ('The moving parts feel uncertain','Security, recovery, reporting, integration and customer records','Sleep At Night',16),
 ('A decision needs another perspective','The Board, report contents and standing-seat options','The Board',19),
]
INDUSTRIES = [
 ('Auto Body & Collision','Insurance referral follow-up, estimates from photos and repair-status texts.'),
 ('Plumbers, HVAC, Contractors','Answered calls, scheduled jobs, field reports and photos, with review requests that go out.'),
 ('Chiropractic & Wellness','Waitlist support, no-show reminders, rebooking nudges and referral follow-up.'),
 ('Restaurants & Hospitality','Reservations, review replies, repeat-customer reminders and cancellation recovery.'),
 ('Professional Services','Lead capture, follow-up and nurture while the team handles client work.'),
 ('Property Inspection','Scheduling through the final report. The current workflow is already in production across Indiana.'),
]
